### ISSUE TITLE
pass GB sheets through pygrambank

### ISSUE THREAD

**Issue by HedvigS** [bedlan/uratyp-1#8]
I would suggest that changes to bedlan/uratyp-1/raw/GB/language-tables should be passed through pygrambank describe and sourcelookup. See #3 for examples of warnings.

If UraTyp team thinks this is a good idea, we may need to modify pygrambank commands somewhat to account for placement of files.

**Comment by xrotwang** [comment]
The "UraTyp team" - as far as converting to CLDF goes - is me.

**Comment by HedvigS** [comment]
I don't understand. Is this not also the repos for UraTyp raw curation?

**Comment by MiinaNo** [comment]
Yes, unfortunately this is true that converting to CLDF = Robert. I do not have these skills...

**Comment by HedvigS** [comment]
> Yes, unfortunately this is true that converting to CLDF = Robert. I do not have these skills...

That's alright. What I'm suggesting  is not related to the conversion to CLDF. I am suggesting that sheets in  bedlan/uratyp-1/raw/GB/language-tables are passed through some checks, like these:  https://github.com/grambank/grambank/wiki/Automatic-quality-checks. 

At Glottobank/Grambank, every time we edit a file we run it through these checks to make sure that the sources line up, that the values make sense etc. We do this little by little each time, it saves us getting a long list of things to see to when we render the CLDF-version.

If you did this here at UraTyp, you could either use pygrambank (we'd have to modify it a little but not much) or you could have your own. Then you'd get warnings like in #4 and #3 right away when edits are made.

**Comment by xrotwang** [comment]
I appreciate that you like pygrambank so much. UraTyp is very different to Grambank, though. At this point, operationally, UraTyp is just Miina and me - and we get by. As creator of pygrambank I know what it can do and what not. And just like Johannes in the case of Grambank, it would be me in the case of UraTyp who'd be running the checks. As far as I can tell, pygrambank isn't necessary for the regular operation of UraTyp updates.

**Comment by HedvigS** [comment]
Okay. I thought that for checking linking to sources and invalid values, pygrambank or something like it might be useful in the day-to-day.

**Comment by xrotwang** [comment]
There really is no "day-to-day". UraTyp is not something - as far as I can tell - that's continuously worked on. It's rather Miina and me (with hours, rather than days or weeks of our time) putting the next release together.

**Comment by HedvigS** [comment]
> There really is no "day-to-day". UraTyp is not something - as far as I can tell - that's continuously worked on. It's rather Miina and me (with hours, rather than days or weeks of our time) putting the next release together.

Okay. I don't know your set-up, it just seemed  useful to me. If you rather handle invalid values, linking references etc some other way then that's alright by me. For the GB sheets specifically, it seemed to me that pygrambank would be handy but please disregard if it isn't.

**Comment by HedvigS** [comment]
It sounds like the suggestion is turned down, if so if @MiinaNo or @xrotwang could please close the issue to confirm.
